### ISSUE TITLE
Implement Ubuntu packages

### ISSUE THREAD

**Issue by stephanosio** [stephanosio/zephyr-crosstool-ng#44]
**TODO**
- [x] Create `zephyr-crosstool-ng` package
- [x] Create `zephyr-crosstool` compiler toolchain packages
- [x] Create `zephyr-qemu` QEMU package

**NOTE**
* All component source code repositories must be hosted on LaunchPad in order to be able to make use of the LaunchPad build servers. This will be handled by creating a "LaunchPad project" and importing the GitHub repositories there (automatically synced).
* Packages will be hosted on the LaunchPad PPA. The PPA will be part of the ["LaunchPad Zephyr RTOS Project" team](https://launchpad.net/~zephyrproject-rtos).

**Comment by stephanosio** [comment]
The Ubuntu (`.deb`) packages are managed in the LaunchPad.

LaunchPad Team where PPAs are hosted: https://launchpad.net/~zephyrproject-rtos
LaunchPad Project for `zephyr-crosstool-ng`: https://launchpad.net/zephyr-crosstool-ng
LaunchPad Project for `zephyr-qemu`: https://launchpad.net/zephyr-qemu
