### ISSUE TITLE
Update to newlib 3.3.0 for Zephyr Xtensa targets

### ISSUE THREAD

**Issue by stephanosio** [stephanosio/zephyr-crosstool-ng#62]
The Zephyr Xtensa targets currently use a [fork of newlib](https://github.com/jcmvbkbc/newlib-xtensa/tree/xtensa) that is based on a very old version of newlib.

Update this to the primary newlib version used by the `zephyr-crosstool-ng` (3.3.0 at the time of writing).

Note that there is a new Xtensa newlib branch that is based on the version 3.2.0; see https://github.com/stephanosio/zephyr-crosstool-ng/issues/35#issuecomment-638052387.

**TODO**
- [ ] Rebase the Xtensa newlib 3.2.0 branch onto 3.3.0
- [ ] Add patches to the newlib-3.3.0 package (or merge them into our newlib fork if #35 gets done before this)
- [ ] Validate the updated newlib in the QEMU (running Zephyr tests should suffice)

**Comment by stephanosio** [comment]
cc @pfalcon @galak @jcmvbkbc
